name: 'Terraform Plan'

on:
  push:
    branches:
      - '**'    
      - '!main'     
  pull_request:
    branches:
      - '**'   
      - '!main'  
jobs:
  
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_region:       ${{ secrets.AWS_REGION }}
      TF_VAR_identifier:       free-tier-db
      TF_VAR_db_username:      ${{ secrets.DB_USERNAME }}
      TF_VAR_db_password:      ${{ secrets.DB_PASSWORD }}
      TF_VAR_key_name:         ${{ secrets.EC2_KEY_NAME }}
      TF_VAR_allowed_ssh_cidr: ${{ secrets.SSH_CIDR }}
      TF_VAR_ssh_cidr:         ${{ secrets.SSH_CIDR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:        ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init  \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ vars.TF_STATE_KEY }}" \
            -backend-config="region=${{ secrets.AWS_REGION }}" 

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan

      - name: Comment Plan on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: tfplan
