name: 'Terraform Apply'

on:
  push:
    branches:
      - main         # or 'main'

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    # Optional: require manual approval in GitHub Environments
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:        ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -reconfigure \
               -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
               -backend-config="key=${{ vars.TF_STATE_KEY }}" \
               -backend-config="region=${{ secrets.AWS_REGION }}" \
               -backend-config="dynamodb_table=${{ vars.TF_LOCK_TABLE }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
